version: ~> 1.0

env:
  global:
    # Doctr deploy key for pcdshub/pcdscalc
    - secure: "LPoSelHMP16qHiHZb96FTnQS2J5//OUnBmFYyHFHJTjFTHfHmk1gSdepXJ7hwHx2AwkSlSCaD5iM4ms7lGxcyZJfrHm07pkqbqz0J3m4C4ideMhu9NWcNaSsjl8/IEMGv3kCQQiw64T9utYIEFutlGg/AstB30VQENyUyeRbY26IkKNqxg+RoUJxb/8oWhMI7fL2u7NOvhlo10+Xo/YYKzwMVQZQC9KhtIbsMfxWFhio3jHe0rtmKqe/um0ENTcWoYFkPiGtZ0JgmWUJNs0rhoiq64Qv+s6G2jDDW75Ok/+l+QipeiE+0gI+dzFZnuGEh1oQ53L3xIyGIqfKHPp+LGqfZ8oi3XgmAES2emufJDWixrhUEQEaGqTSYlF/Dd2L8+k3bUN2f6W4I24ETJ2eCnJdWTKFdzi7i0mlVJs0XbJ3MCY3sjlE+GFGu7WcpQRO6tbdhN3b9fZfuYIYLxNCcJKsjJD2MbX8j6JyH6r9A3x+prycU2ZKSjEjW5ituZvDDWwsn9EBJW4vbBX821cDghR2fBIFAxY4IGMQ8gBox4kNa/k9bYvVjD+TholqP5TkPj5e5W/SldbTqwFkwaCg9qRJlaNnfZqKkF+BCr73o1ecZ83oGyZfXfFmi7jemk2MSEv36iNIl/Z1e43nJw3YbR4wuq0yO7RpH97H3GWfbq4="
    # enable the usage of versions menu which allow versioning of the docs
    # pages and not only the master branch
    - DOCTR_VERSIONS_MENU="1"
    # Dependency files used to build the documentation (space separated)
    - DOCS_REQUIREMENTS="doc-requirements.txt dev-requirements.txt requirements.txt"
    # Options to be passed to flake8 for package linting. Usually this is just
    # the package name but you can enable other flake8 options via this config
    - PYTHON_LINT_OPTIONS="pcdscalc"

    # The name of the conda package
    - CONDA_PACKAGE="pcdscalc"
    # The folder containing the conda recipe (meta.yaml)
    - CONDA_RECIPE_FOLDER="conda-recipe"

    # Requirements file with contents for tests dependencies
    - CONDA_REQUIREMENTS="dev-requirements.txt"

# Uncomment this block if you would like to make PIP test an allowed failure
#jobs:
#  allow_failures:
#    # This makes the PIP based Python 3.6 optional for passing.
#    # Remove this block if passing tests with PIP is mandatory for your
#    # package
#    - name: "Python 3.6 - PIP"

import:
  - pcdshub/pcds-ci-helpers:travis/shared_configs/standard-python-conda.yml
