{% set data = load_setup_py_data() %}


package:
    name: pcdscalc
    version: {{ data.get('version') }}

source:
    path: ..

build:
    number: 1
    noarch: python

requirements:
    build:
      - python >=3.6
      - setuptools
    run:
      - python >=3.6
      - numpy
      - periodictable
      - scipy

test:
    imports:
      - pcdscalc
    requires:
      - pytest

about:
  home: https://github.com/pcdshub/pcdscalc
  license: SLAC Open License
  summary: PCDS Calculation Routines
